version: '1.0'

networks:
  configer:

services:
  postgres:
    container_name: postgres
    image: postgres:14.4
    environment:
      - PGPORT=5431
      - POSTGRES_USER=configer
      - POSTGRES_PASSWORD=6aa26d02-14b2-4158-8028-22da1f59b07c
      - POSTGRES_DB=configer
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5431:5431
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - configer

  configer:
    container_name: configer
    build:
      context: .
    env_file:
      - .production.env
    ports:
      - 5100:5000
    command: npm run start
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - configer

volumes:
  pgdata: